### ISSUE TITLE
Add open source license to project

### ISSUE THREAD

**Issue by dangerp** [jrochkind/ipaddr_range_set#2]
Can you please add an open source license to this project so that others can use it?  Github provides details on how to do so here: https://help.github.com/articles/adding-a-license-to-a-repository/.  The MIT license is pretty popular.

Without a license, all rights are reserved and others can't use your project for any purpose.  You can read more at https://help.github.com/articles/licensing-a-repository/

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by jrochkind** [comment]
no prob there you go
